import type { Metadata } from "next";
import "./globals.css";
import { pretendard } from "@/styles/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable} h-full`}>
      <body className="flex h-dvh w-full flex-col overflow-hidden font-sans antialiased">
        <div className="mx-auto flex h-dvh w-full max-w-(--app-max-width) flex-col bg-white">
          <main className="flex min-h-0 flex-1 flex-col overflow-y-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
